name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.0'  
      
      - name: Install npm dependencies
        run: npm install --production

      - name: Install Jest
        run: npm i jest -D

      - name: Run tests using jest
        run: npm test
